### ISSUE TITLE
Treffen

### ISSUE THREAD

**Issue by Lacritz** [ProPra16/programmierpraktikum-abschlussprojekt-nosuchfieldexception#1]
Hi zusammen, ich heiße Timo Grün und bin euer Tutor für das Gruppenprojekt.

Zwecks eines Treffens wäre es gut von euch einen Termin genannt zu bekommen, wann und wo ihr euch als Gruppe trefft - so dass ich einmal vorbei kommen kann!

Meldet euch am besten einfach per Mail bei mir:
Timo.Gruen@uni-duesseldorf.de

Gruß 
Timo

**Comment by SPRTCS** [comment]
Hallo Timo,
Ich wollte dich darüber in Kenntnis setzten, dass wir uns Dienstag das
nächste mal treffen. Um 9 Uhr in der Wanne.

Gruß
Arman
Timo Grün notifications@github.com schrieb am So., 3. Juli 2016 um 16:15:
